sudo: required
language: generic
services:
    - docker

before_install: 
    - docker build -t menoelpis/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true menoelpis/docker-react npm run test
